### ISSUE TITLE
画像アップロードコンポーネント新規実装

### ISSUE THREAD

**Issue by kimuniiii** [kimuniiii/Personal-Development#32]
## 機能要件（MUST要求）

- アップロードする画像のサイズは10MB以内
- プロフィール編集画面では「アップロードできる画像の枚数」は「1枚のみ」にする
- 商品登録画面では「アップロードできる画像の枚数」は「3枚以下」にする
- 商品登録画面で同じ画像をアップロードした場合は弾くようなロジックを実装する
- 条件に反した場合はエラーを表示する
- 画像のみをアップロードするようにする

## 非機能要件（WANT要求）

- 画像のサイズを圧縮させる
- 最大「何MB以内」みたいにMAXサイズを決める

**Comment by kimuniiii** [comment]
## 仕事の進め方

- プレゼンテーション部分の実装を完了させる
- ビジネスロジック部分の実装を完了させる

**Comment by kimuniiii** [comment]
## 2021年8月17日（火）時点での画像アップロードコンポーネント

<img width="871" alt="スクリーンショット 2021-08-18 1 15 15" src="https://user-images.githubusercontent.com/59758368/129762739-d9d78884-30a3-47b2-8fde-fffb9e4f9f15.png">

**Comment by kimuniiii** [comment]
## ファイルを選択ボタンをどうやってカスタマイズ実装すればいいか？

- デフォルトの`<input>`の見た目を変えるのは難しいので非表示にしてしまう
- そのうえで`<label>`を装飾し、ボタンらしく見せています

```html
<label class="upload-label">
  ファイルを選択
  <input type="file">
</label>
```

```css
.upload-label {
  display: inline-block;
  cursor: pointer; /* カーソルを指に */
  margin: 1em 0; /* まわりの余白 */
  padding: .7em 1em; /* 文字まわりの余白 */
  line-height: 1.4; /* 行間 */
  background: #3e8bff; /* 背景色 */
  color: #FFF; /* 文字色 */
  font-size: 0.95em; /* フォントサイズ */
  border-radius: 2.5em; /* 角の丸み */
  transition: 0.2s; /* ホバーをなめらかに */
}
/* ホバー時 */
.upload-label:hover {
  box-shadow: 0 8px 10px -2px rgba(0, 0, 0, 0.2); /* 影を表示 */
}
/* inputは隠す */
.upload-label input {
  display: none;
}
```
