### ISSUE TITLE
Hasura を用いたセットアップ手順をまとめる

### ISSUE THREAD

**Issue by kimuniiii** [kimuniiii/Personal-Development#39]
## セットアップ手順

1. Hasura を Docker Compose で立ち上げる
2. データベースに「テーブル」を作成する
3. GraphQLで データベース から値を取得する（query）
4. GraphQLで データベースにアイテムを追加する（mutation）
5. ここまでの動作確認が完了したら、個人開発のDB設計を行う

**Comment by kimuniiii** [comment]
## Hasura を Docker Compose で立ち上げる

```yaml
version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.0.7
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
```

## 参考文献

[hasura | GraphQL Engine | GitHub](https://github.com/hasura/graphql-engine/blob/stable/install-manifests/docker-compose/docker-compose.yaml)
